config/routes.rb
Rails.application.routes.draw do
  root "items#index"

  resources :items do 
    member do
      get :refresh
    end
  end
end

app/models/item.rb
# encoding: utf-8
class Item < ActiveRecord::Base
  include ItemHttpRequest

  validates :uri,   presence: true
  validates :price, presence: true

  scope :live,     -> { where(archive: false) }
  scope :archived, -> { where(archive: true) }

  has_many :stages
  has_many :tag_stages,    -> { where(category: Stage.categories[:tag])},    class_name: "Stage"
  has_many :random_stages, -> { where(category: Stage.categories[:random])}, class_name: "Stage"
  
  def latest_tag_stage
    tag_stages.order(:created_at).last
  end

  def first_tag_stage
    tag_stages.order(:created_at).first
  end

  def first_day_tag_stage
    latest_tag_stage_at(self.on_sale_date)
  end

  def latest_tag_stage_at(a_date)
    latest_tag_stage_before(a_date + 1)
  end

  def latest_tag_stage_before(a_date)
    tag_stages.where("created_at < ?", a_date.try(:to_time)).order(:created_at).last
  end

  def latest_random_stage
    random_stages.order(:created_at).last
  end

  def pre_sale?
    on_sale_date > Date.today
  end

  def on_sale?
    on_sale_date <= Date.today && off_sale_date > Date.today
  end

  def off_sale?
    off_sale_date <= Date.today
  end

  def first_day?
    on_sale_date == Date.today
  end

  after_initialize :build_sale_date
  def build_sale_date
    if on_sale_date.nil?
      self.on_sale_date  = Date.today + 1
    end

    if off_sale_date.nil?
      self.off_sale_date = Date.today + 9
    end
  end

  # ===== ===== ===== ===== ===== 

  def create_tag_stage
    self.tag_stages.create
  end

  def create_random_stage
    self.random_stages.create
  end

  def hourly_tag_stage
    return nil if (self.pre_sale? || self.off_sale?)
    return nil if (Time.now.hour <= 9 && self.first_day?)
    return self.create_tag_stage
  end

  def refresh_random_stage
    if self.latest_random_stage && (Time.now - self.latest_random_stage.created_at) <= 10
      self.latest_random_stage
    else
      self.create_random_stage
    end
  end

  after_create :refresh_random_stage

  def archive!
    self.update(archive: true)
  end

  def unarchive!
    self.update(archive: false)
  end
end

app/models/item_http_request.rb
# encoding: utf-8
module ItemHttpRequest
  # fetch api data content
  VIP_API_URI_BASE = "http://stock.vip.com/detail?callback=detail_stock&merchandiseId=%s"
  TIMEOUT_GAP      = 10
  
  def vip_id
    match = self.uri.match(/\-(\d*)\.html/)
    if match
      match[1]
    else
      nil
    end
  end

  def vip_api_uri
    VIP_API_URI_BASE % vip_id
  end

  def fetch_api_current_content
    body_str = ""
    begin
      body_str    = HTTParty.get(self.vip_api_uri, timeout: TIMEOUT_GAP).body
    rescue Exception => e
      puts e
    end
    content_str = body_str.gsub(/^detail_stock\({"items":/, "").gsub(/}\)$/, "")
    content_str
  end

  def examine_web_content
    if self.uri.present?
      doc = nil
      
      begin
        doc = Nokogiri::HTML HTTParty.get(self.uri, timeout: 10).body
      rescue Exception => e
        puts e
      end
      
      if doc
        # name = doc.css(".shan_description strong").try(:first).try(:content)
        name = doc.css(".detail_info_htmlMod strong").try(:first).try(:content)
        code = nil

        # doc.css(".shan_description p").each do |p|
        doc.css(".detail_info_htmlMod p").each do |p|
          rst = p.content.match(/商品货号：?(.*)$/) 
          if rst
            code = rst[1] 
            break
          end
        end
        # price = doc.css(".shan_info .shan_price strong").first.content.to_f
        price = doc.css(".products_price .p_price_vip em").first.content.to_f
        # image_uri = doc.css(".art_area img").first.attr("src")
        image_uri = doc.css(".productpic img").first.attr("src")

        self.name  = name
        self.code  = code
        self.price = price
        self.image_uri = image_uri
      end
    end

    self
  end
end

app/models/stage.rb
# encoding: utf-8
class Stage < ActiveRecord::Base
  belongs_to :item

  enum category: { tag: 0, random: 1 }
  enum status:   { ok: 0, short: 1, long: 2 }

  before_save :calc

  def list
    self.content ? JSON.parse(self.content) : []
  end

  def calc
    self.content = self.item.fetch_api_current_content
    self.sum     = list.sum{|i| i["saled"]} if self.list
  end

  def code
    "#{((created_at.to_date - item.on_sale_date).to_i + 1)}.#{self.created_at.hour}"
  end

  def saled_today
    # 如果当天刚上线
    if self.item.on_sale_date == self.created_at.to_date
      self.sum

    # 如果已经上线数天，找到前一天的最后一个tag
    else
      last_stage_tag = self.item.latest_tag_stage_before(self.created_at.to_date)
      if last_stage_tag
        self.sum - last_stage_tag.sum
      else
        self.sum
      end
    end
  end
end

app/models/work.rb
class Work
  def self.start
    puts "#{Time.now} work start ..."
    Item.live.each do |i|
      i.hourly_tag_stage
    end
    puts "--- Done."
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
end

app/controllers/items_controller.rb
# encoding: utf-8
class ItemsController < ApplicationController
  def index
    if params[:scope] == 'live'
      @items = Item.live.includes(:stages)
    elsif params[:scope] == 'archive'
      @items = Item.archived.includes(:stages)
    elsif params[:scope] == 'all'
      @items = Item.includes(:stages)
    else
      @items = Item.live.includes(:stages)
    end

    @items = @items.order('on_sale_date DESC')
  end

  def new
    @item = Item.new params.permit(:uri)
    @item.examine_web_content if @item.uri.present?
    flash[:alert] = "添加失败，请确定uri，价格都有写明确。"
  end

  def create
    @item = Item.new params.require(:item).permit(:uri, :name, :code, :price, :image_uri, :on_sale_date, :off_sale_date) 
    @item.examine_web_content if !@item.price
    if @item.save
      flash[:notice] = '添加完成'
      redirect_to root_path
    else
      flash[:alert]  = '添加失败，请确定uri，价格都有写明确。'
      render :new
    end
  end

  def show
    @item = Item.find params[:id]
  end

  def edit
    @item = Item.find params[:id]
  end

  def update
    @item = Item.find params[:id]
    @item.update params.require(:item).permit(:uri, :name, :code, :price, :image_uri, :on_sale_date, :off_sale_date) 
    redirect_to root_path
  end

  def refresh
    @item = Item.find params[:id]
    @item.refresh_random_stage
    if params[:from] && params[:from] == "index"
      redirect_to items_path
    else
      redirect_to item_path
    end
  end

  def destroy
    @item = Item.find params[:id]
    if params[:archive].to_i == 1
      unless @item.archive
        @item.archive!
      else
        @item.unarchive!
      end
    else
      @item.destroy
    end
    redirect_to items_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/edit.html.haml
.container
  .row
    .col-md-8
      .panel.panel-primary
        .panel-heading
          请输入商品链接地址 URL

        .panel-body
          = simple_form_for @item, wrapper: :bootstrap_hf_37, html: { class: 'form-horizontal login-form' } do |f|
            = f.input :uri,   label: "团购uri", label_html: { class: "col-md-3" }, required: true
            = f.input :name,  label: "名称",    label_html: { class: "col-md-3" }
            = f.input :price, label: "价格",    label_html: { class: "col-md-3" }
            = f.input :code,  label: "代码",    label_html: { class: "col-md-3" }
            = f.input :on_sale_date,
                      label: "开团日期",
                      label_html: { class: "col-md-3" },
                      input_html: { class: "col-md-1", style: "width: 30%;" }
            = f.input :off_sale_date,
                      label: "结束日期",
                      label_html: { class: "col-md-3" },
                      input_html: { class: "col-md-1", style: "width: 30%;" }

            - if @item.image_uri
              = image_tag @item.image_uri, style: "margin-bottom: 14px;"
              = f.hidden_field :image_uri
            - else
              = f.input :image_uri, label: "图片uri", label_html: { class: "col-md-3" }  

            .form-group 
              .col-md-7.col-md-offset-3
                = f.submit "提交", class: "btn btn-large btn-primary"

app/views/items/index.html.haml
%table.table.table-hover
  %thead
    %tr
      %th.col-md-1 #
      %th.col-md-2 商品信息
      %th.col-md-2 图片
      %th.col-md-1 第一次
      %th.col-md-1 第一天
      %th.col-md-1 当天
      %th.col-md-1 当前
  %tbody
    - @items.each do |item|
      %tr
        %td= link_to item.code, item, target: :blank

        %td
          %ul.list-unstyled
            %li= link_to item.name, item.uri, target: :blank
            %li= item.price.to_s + ' rmb'
            %li
              = item.on_sale_date.strftime("%m-%d")
              \~
              = item.off_sale_date.strftime("%m-%d")
            .btn-group
              = link_to "刷新", refresh_item_path(item, from: "index"), class: "btn btn-sm btn-default"
              %button.btn.btn-sm.btn-default.dropdown-toggle{data: {toggle: "dropdown"}}
                %span.caret
                %span.sr-only Toggle Dropdown
              %ul.dropdown-menu{role: "menu"}
                %li= link_to "编辑", edit_item_path(item)
                %li
                  - txt = item.archive ? "激活" : "归档"
                  = link_to txt, item_path(item, archive: 1), method: :delete, data: {confirm: "确定#{txt}？"}
                - if item.archive
                  %li= link_to "删除", item, method: :delete, data: {confirm: "确定删除？"}

        %td= image_tag item.image_uri, width: "280px"

        %td= render item.first_tag_stage     if item.first_tag_stage
        %td= render item.first_day_tag_stage if item.first_day_tag_stage
        %td= render item.latest_tag_stage    if item.latest_tag_stage
        %td= render item.latest_random_stage if item.latest_random_stage

app/views/items/new.html.haml
.container
  .row
    .col-md-8
      - if flash[:alert]
        .alert.alert-danger.fade.in
          %button{type: "button", class: "close", data: {dismiss: "alert"}}
            %span{"aria-hidden" => "true"} &times;
            %span.sr-only close
          = flash[:alert]
      .panel.panel-primary
        .panel-heading
          请输入商品链接地址 URL

        .panel-body
          = simple_form_for @item, wrapper: :bootstrap_hf_37, html: { class: 'form-horizontal login-form' } do |f|
            = f.input :uri,   label: "团购uri", label_html: { class: "col-md-3" }, required: true, hint: link_to("校验", new_item_path, id: "check_link", data: {item_new_path: new_item_path})
            = f.input :name,  label: "名称",    label_html: { class: "col-md-3" }
            = f.input :price, label: "价格",    label_html: { class: "col-md-3" }
            = f.input :code,  label: "代码",    label_html: { class: "col-md-3" }
            = f.input :on_sale_date,
                      label: "开团日期",
                      label_html: { class: "col-md-3" },
                      input_html: { class: "col-md-1", style: "width: 30%;" }
            = f.input :off_sale_date,
                      label: "结束日期",
                      label_html: { class: "col-md-3" },
                      input_html: { class: "col-md-1", style: "width: 30%;" }

            - if @item.image_uri
              = image_tag @item.image_uri, style: "margin-bottom: 14px;"
              = f.hidden_field :image_uri
            - else
              = f.input :image_uri, label: "图片uri", label_html: { class: "col-md-3" }  

            .form-group 
              .col-md-7.col-md-offset-3
                = f.submit "提交", class: "btn btn-large btn-primary"

app/views/items/show.html.haml
.container
  .row
    .col-md-4
      %ul.list-unstyled
        %li= image_tag @item.image_uri, width: "280px"
        %li= @item.code
        %li= link_to @item.name, @item.uri, target: :blank
        %li= @item.price.to_s + ' rmb'
        %li
          = @item.on_sale_date.strftime("%m-%d")
          \~
          = @item.off_sale_date.strftime("%m-%d")
        %hr
        %li= render @item.latest_random_stage if @item.latest_random_stage
        %hr
        %li= link_to "刷新", refresh_item_path(@item), class: "btn btn-sm btn-success"
    .col-md-8

      %table.table.table-bordered
        %thead
          %tr
            %th 时间
            %th 累计销量
            %th 当天销量
            %th 详情
            %th 状态
        %tbody
          - last_day = Date.today > @item.off_sale_date ? @item.off_sale_date : Date.today
          - (@item.on_sale_date .. last_day).each do |a_date|
            - stage = @item.latest_tag_stage_at(a_date)
            - if stage # && stage.created_at.to_date == a_date
              = render "stages/stage_daily_in_detail", stage: stage, date: a_date
            - else
              = render "stages/stage_blank_in_detail", date: a_date

      %table.table.table-bordered
        %thead
          %tr
            %th 时间
            %th 累计销量
            %th 详情
            %th 状态
        %tbody
          - @item.tag_stages.each do |stage|
            = render "stages/stage_in_list", stage: stage

app/views/layouts/_header.html.haml
%nav.navbar.navbar-default
  .container
    .navbar-header
      = link_to "VIP", "/", class: "navbar-brand"

    %ul.nav.navbar-nav.navbar-right
      %li{class: "#{(params[:scope] == 'live' || params[:scope].blank?) ? 'active' : ''}"}
        = link_to "活跃商品", items_path(scope: "live")
      %li{class: "#{params[:scope] == 'archive' ? 'active' : ''}"}
        = link_to "归档商品", items_path(scope: "archive")
      %li{class: "#{params[:scope] == 'all' ? 'active' : ''}"}
        = link_to "全部商品", items_path(scope: "all")
      %li
        = link_to "添加+", new_item_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title BigData
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'SMECC JINING'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  
  %body
    = render "layouts/header"
    = yield
    / = render "layouts/footer"

app/views/stages/_stage.html.haml
%strong.text-success
  - if stage.sum
    = "SUM: #{stage.sum.to_s} (#{(stage.sum * stage.item.price / 10000.0).round(2)}万)" 
  - else
    ？

  - if stage.saled_today
    = "ADD: #{stage.saled_today.to_s} (#{(stage.saled_today * stage.item.price / 10000.0).round(2)}万)" 
  - else
    ？      

%ul.list-unstyled
  - stage.list.each do |i|
    %li
      - if i["stock"] == 0 || i["type"] == 1 # || i["ptype"] == 1
        %span.label.label-danger
          = i["name"] + " · " + i["saled"].to_s + " · " + "断"
      - else
        = i["name"] + " · " + i["saled"].to_s
  - if stage.random?
    %li.text-muted= time_ago_in_words(stage.created_at)
  - else
    %li.text-muted= stage.code

app/views/stages/_stage_blank_in_detail.html.haml
%tr
  %td
    = date.strftime("%m-%d")
  %td
    %strong.text-success
      ？
  %td
    %strong.text-success
      ？
  %td
    ?
  %td
    %span.glyphicon.glyphicon-eye-close.text-warning

app/views/stages/_stage_daily_in_detail.html.haml
%tr
  %td
    = date.strftime("%m-%d")
    %span.text-muted
      ·
      = stage.created_at.localtime.strftime("%H:%m")
  %td
    %strong.text-success
      = "#{stage.sum.to_s} (#{(stage.sum * stage.item.price / 10000.0).round(2)}万)" 
  %td
    %strong.text-success
      = "#{stage.saled_today.to_s} (#{(stage.saled_today * stage.item.price / 10000.0).round(2)}万)" 
  %td
    %ul.list-inline
      - stage.list.each do |i|
        %li
          - if i["stock"] == 0 || i["type"] == 1 # || i["ptype"] == 1
            %span.label.label-danger
              = i["name"] + " · " + i["saled"].to_s + " · " + "断"
          - else
            = i["name"] + " · " + i["saled"].to_s
  %td
    %span.glyphicon.glyphicon-ok-circle.text-success

app/views/stages/_stage_in_list.html.haml
%tr
  %td= stage.created_at.localtime.strftime("%m-%d %H:%m")
  %td
    %strong.text-success= "#{stage.sum.to_s} (#{(stage.sum * stage.item.price / 10000.0).round(2)}万)" 
  %td
    %ul.list-inline
      - stage.list.each do |i|
        %li
          - if i["stock"] == 0 || i["type"] == 1 # || i["ptype"] == 1
            %span.label.label-danger
              = i["name"] + " · " + i["saled"].to_s + " · " + "断"
          - else
            = i["name"] + " · " + i["saled"].to_s
  %td
    ok